global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tta-observability'
    static_configs:
      - targets: ['host.docker.internal:9464']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
>>>>>>> main
    static_configs:
      - targets: ['localhost:9090']
