# This is a config for E2B sandbox template.
# You can use template ID (3xmp0rmfztawhlpysu4v) or template name (tta-ml-minimal) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("tta-ml-minimal") # Sync sandbox
# sandbox = await AsyncSandbox.create("tta-ml-minimal") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('tta-ml-minimal')

team_id = "faaaabcb-397c-403a-a781-344e0586de27"
dockerfile = "e2b.Dockerfile.ml-minimal"
template_name = "tta-ml-minimal"
template_id = "3xmp0rmfztawhlpysu4v"
