# This is a config for E2B sandbox template.
# You can use template ID (oefy20iwv272ehx2kqf4) or template name (tta-debug-minimal) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("tta-debug-minimal") # Sync sandbox
# sandbox = await AsyncSandbox.create("tta-debug-minimal") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('tta-debug-minimal')

team_id = "faaaabcb-397c-403a-a781-344e0586de27"
dockerfile = "e2b.Dockerfile.debug-minimal"
template_name = "tta-debug-minimal"
template_id = "oefy20iwv272ehx2kqf4"
